name: Build and push Docker image

on:
  push:
    branches: [ master ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'

#      - name: Build Dremio
#        run: |
#          mvn clean install -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ZAPATABOT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ZAPATABOT_DOCKERHUB_PASSWORD }}

      - name: Set image tag
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "Image tag: $SHA_SHORT"
          echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: distribution
          file: distribution/docker/Dockerfile
          push: true
          tags: alparslanavci/dremio:${{ env.SHA_SHORT }}
